# Week 1
## MATH 189 • Data Analysis & Inference • Sp 2024
### Siddharth Vishwanath

# %load latexdefs.tex
$$
\newcommand{\sumn}{\sum^{i=1}^n}
\newcommand{\R}{\mathbb{R}}
\newcommand{\defeq}{\stackrel{\small\bullet}{=}}
\newcommand{\eq}[1]{\begin{aligned}#1\end{aligned}}
\newcommand{\bea}{\begin{aligned}}
\newcommand{\eea}{\end{aligned}}
\newcommand{\tr}{^{\top}}
\newcommand{\ra}{\rangle}
\newcommand{\la}{\langle}
\newcommand{\pr}{{\mathbb P}}
\newcommand{\qr}{{\mathbb Q}}
\newcommand{\xv}{{\boldsymbol{x}}}
\newcommand{\av}{{\boldsymbol{a}}}
\newcommand{\bv}{{\boldsymbol{b}}}
\newcommand{\cv}{{\boldsymbol{c}}}
\newcommand{\dv}{{\boldsymbol{d}}}
\newcommand{\ev}{{\boldsymbol{e}}}
\newcommand{\fv}{{\boldsymbol{f}}}
\newcommand{\gv}{{\boldsymbol{g}}}
\newcommand{\hv}{{\boldsymbol{h}}}
\newcommand{\nv}{{\boldsymbol{n}}}
\newcommand{\sv}{{\boldsymbol{s}}}
\newcommand{\tv}{{\boldsymbol{t}}}
\newcommand{\uv}{{\boldsymbol{u}}}
\newcommand{\vv}{{\boldsymbol{v}}}
\newcommand{\wv}{{\boldsymbol{w}}}
\newcommand{\zerov}{{\mathbf{0}}}
\newcommand{\onev}{{\mathbf{0}}}
\newcommand{\phiv}{{\boldsymbol{\phi}}}
\newcommand{\cc}{{\check{C}}}
% \newcommand{\xv}{{\boldsymbol{x}}}
\newcommand{\Xv}{{\boldsymbol{X}\!}}
\newcommand{\yv}{{\boldsymbol{y}}}
\newcommand{\Yv}{{\boldsymbol{Y}}}
\newcommand{\zv}{{\boldsymbol{z}}}
\newcommand{\Zv}{{\boldsymbol{Z}}}
\newcommand{\Iv}{{\boldsymbol{I}}}
\newcommand{\Jv}{{\boldsymbol{J}}}
\newcommand{\Cv}{{\boldsymbol{C}}}
\newcommand{\Ev}{{\boldsymbol{E}}}
\newcommand{\Fv}{{\boldsymbol{F}}}
\newcommand{\Gv}{{\boldsymbol{G}}}
\newcommand{\Hv}{{\boldsymbol{H}}}
\newcommand{\alphav}{{\boldsymbol{\alpha}}}
\newcommand{\epsilonv}{{\boldsymbol{\epsilon}}}
\newcommand{\betav}{{\boldsymbol{\beta}}}
\newcommand{\deltav}{{\boldsymbol{\delta}}}
\newcommand{\gammav}{{\boldsymbol{\gamma}}}
\newcommand{\etav}{{\boldsymbol{\eta}}}
\newcommand{\piv}{{\boldsymbol{\pi}}}
\newcommand{\thetav}{{\boldsymbol{\theta}}}
\newcommand{\tauv}{{\boldsymbol{\tau}}}
\newcommand{\muv}{{\boldsymbol{\mu}}}
\newcommand{\sd}{\text{SD}}
\newcommand{\se}{\text{SE}}
\newcommand{\med}{\text{median}}
\newcommand{\median}{\text{median}}
\newcommand{\Ber}{{\text{Ber}}}
\newcommand{\Bin}{{\text{Bin}}}
\newcommand{\Geo}{{\text{Geo}}}
\newcommand{\Unif}{{\text{Unif}}}
\newcommand{\Poi}{{\text{Poi}}}
\newcommand{\Exp}{{\text{Exp}}}
\newcommand{\Chisq}{{\chi^2}}
\renewcommand{\N}{\mathbb{N}}
\newcommand{\iid}{{\stackrel{iid}{\sim}}}
\newcommand{\px}{p^{X}}
\newcommand{\fx}{f^{X}}
\newcommand{\Fx}{F^{X}}
\newcommand{\py}{p^{Y}}
\newcommand{\pxy}{p^{X,Y}}
\newcommand{\po}{{p^0}}
\newcommand{\pa}{{p_a}}
\newcommand{\Xbar}{\overline{X}}
\newcommand{\Ybar}{\overline{Y}}
\newcommand{\Zbar}{\overline{Z}}
\newcommand{\nXbar}{n \cdot \overline{X}}
\newcommand{\nYbar}{n \cdot \overline{Y}}
\newcommand{\nZbar}{n \cdot \overline{Z}}
\newcommand{\Xn}{X_1, X_2, \dots, X_n}
\newcommand{\Xm}{{X_1, X_2, \dots, X_m}}
\newcommand{\Yn}{Y_1, Y_2, \dots, Y_n}
\newcommand{\Ym}{{Y_1, Y_2, \dots, Y_m}}
\newcommand{\sumXn}{X_1 + X_2 + \dots + X_n}
\newcommand{\sumym}{Y_1 + Y_2 + \dots + Y_m}
\renewcommand{\la}{\ell_\alpha}
\newcommand{\ua}{u_\alpha}
\newcommand{\at}{{\alpha/2}}
\newcommand{\mux}{\mu_{X}}
\newcommand{\muy}{\mu_{Y}}
\newcommand{\sx}{\sigma_{X}}
\newcommand{\sy}{\sigma_{Y}}
\newcommand{\pvalue}{$p$-value}
\newcommand{\Ho}{H_{0}}
\newcommand{\Ha}{H_{a}}
\newcommand{\betav}{\boldsymbol{\beta}}
$$

In [1]:
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
import ipywidgets
from ipywidgets import interact, interactive, fixed, interact_manual
%matplotlib inline

/var/folders/9y/mgt7f5vs291bqw087d9p6qz00000gn/T/ipykernel_57595/4234412355.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## Agenda
---

1. Introduction
2. Course Logistics
3. Basics of Markdown and $\LaTeX$
4. Linear Algebra Review
    * Vectors, matrices, operations
    * Eigenvalues and eigenvectors
5. Review of Probability
    * Probability, random variables, distributions
    * Expectation, variance, covariance
6. Data wrangling

### Course Logistics

* Jupyter notebooks:
    * [Anaconda](https://www.anaconda.com/products/individual)
    * [Anaconda Cloud](https://anaconda.cloud/getting-started)
    * [UCSD DataHub](https://datahub.ucsd.edu/hub/spawn)
    * [Google Colab](https://colab.google/)
* [Course Information and Syllabus](https://canvas.ucsd.edu/courses/55191)
* [Class Github repository](https://github.com/ucsd-math189/sp24)

This is a markdown cell

# Basics of Markdown and $\LaTeX$

## §1.1: Creating sections for your document

## Level 2
---
### Level 3
#### Level 4

## §1.2: Bullet Lists and Numbered Lists

This is a enumeration list:

1. Item 1
  1. Subitem 1
        1. Subsubitem 1
        1. SUbsubitem 2
    1. Subitem 2
1. Item 2
1. Item 3

## §1.3: Math

This is a math display

$$
\begin{aligned}
\text{Var}(X) 
&= \mathbb{E} (X - \mathbb{E}(X))^2\\
&= \frac{1}{n-1} \sum_{i=1}^n (X_i - \overline{X})^2 \\
\end{aligned}
$$ 

where the sentence continues here

### §1.3.1 Boxed & Colored Equations

This is the expression for the sample mean:

this is inline math $
% \boxed{ 
    \color{dodgerblue}{ 
        \frac{1}{n}\sum_{i=1}^n X_i = \overline{X}
     }
%   }
$ and the sentence continues here

### §1.3.2 Math Macros

$$
\newcommand{\Xn}{X_1, X_2, \cdots, X_n}
\newcommand{\Dt}{D(\theta)}
$$

$\Xn$ is sampled iid from a distribution $\Dt$

# §2. Basics of Python

## §2.1: Int, Float, Booleans, Strings

In [2]:
"abcde" + "fgh"

'abcdefgh'

#### §2.1.2 Arithmetic operations (+, -, *, /, %, //, **)

In [3]:
13 ** 4

28561

## §2.2: Arrays, Tuples, Dicts

In [4]:
## array
[1, 2,  3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [5]:
## tuple
type((1, 2, 3))

tuple

In [6]:
## dict
for k, v in {"a": 1, "b": 2, "c": math.pi}.items():
    print(f'k = {k}, v= {v}')

k = a, v= 1
k = b, v= 2
k = c, v= 3.141592653589793


In [7]:
## sets
a = {1, 2, 3, 4, 4, 5}
b = {4, 5, 7}
a.symmetric_difference(b)

{1, 2, 3, 7}

## §2.3: Control Flow

In [8]:
## if-else
for i in range(1, 10):
    if i % 2 == 0:
        print(f'{i} is even')
    else:
        print(f'{i} is odd')

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [9]:
# if-elif-else
for i in range(1, 10):
    if i % 4 == 0:
        print(f'{i} is a multiple of 4')
    elif i % 2 == 0:
        print(f'{i} is even')
    else:
        print(f'{i} is odd')

1 is odd
2 is even
3 is odd
4 is a multiple of 4
5 is odd
6 is even
7 is odd
8 is a multiple of 4
9 is odd


In [10]:
# while
n = 0
while n < 10:
    print(f'n = {n}')
    n += 1

n = 0
n = 1
n = 2
n = 3
n = 4
n = 5
n = 6
n = 7
n = 8
n = 9


## §2.4: Functions

In [11]:
def fibonacci(n):
    return 0 if n == 0 else 1 if n == 1 else fibonacci(n-1) + fibonacci(n-2)

## §2.4.1: Anonymous Functions

In [12]:
fib  = lambda n: 0 if n == 0 else 1 if n==1 else fib(n-1) + fib(n-2)

# §3 Vectors and Linear Algebra

In [32]:
# These are plotting functions for the interactive visualizations
def plot_v(v1, v2, v3):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.quiver(0, 0, 0, v1, v2, v3)
    ax.set_xlim([-3, 3]); ax.set_ylim([-3, 3]); ax.set_zlim([-3, 3])
    ax.set_xlabel('X'); ax.set_ylabel('Y'); ax.set_zlabel('Z')
    # camera angle
    # ax.view_init(elev=20, azim=45)
    plt.tight_layout()
    plt.show()

def plot_vw(v1, v2, v3, w1, w2, w3):
    v = np.array([v1, v2, v3])
    w = np.array([w1, w2, w3])
    vw = v + w
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.quiver(0, 0, 0, *v)
    ax.quiver(0, 0, 0, *w, color='black')
    ax.quiver(0, 0, 0, *vw, color='red')
    ax.set_xlim([-3, 3]); ax.set_ylim([-3, 3]); ax.set_zlim([-3, 3])
    ax.set_xlabel('X'); ax.set_ylabel('Y'); ax.set_zlabel('Z')
    # camera angle
    # ax.view_init(elev=20, azim=45)
    plt.show()
  
def plot_dotv(u1=1, u2=1, v1=1,v2=1):
    u = np.array([u1, u2])
    v = np.array([v1, v2])
    uv = np.dot(u, v)
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.quiver(0, 0, *v, angles='xy', scale_units='xy', scale=1)
    ax.quiver(0, 0, *u, angles='xy', scale_units='xy', scale=1)
    ax.set_xlim([-3, 3]); ax.set_ylim([-3, 3])
    ax.set_title(f'dot-product = {uv}')
    plt.tight_layout()
    plt.show()
    
def plot_crossv(u1=1, u2=1, v1=1,v2=1):
    u = np.array([u1, u1, u2])
    v = np.array([v1, 0, v2])
    uv = np.cross(u, v)
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.quiver(0, 0, 0, *v,)
    ax.quiver(0, 0, 0, *u,)
    ax.quiver(0, 0, 0, *uv, color='red')
    ax.set_xlim([-3, 3]); ax.set_ylim([-3, 3]); ax.set_zlim([-3, 3])
    ax.set_title(f'cross-product = {uv}')
    plt.tight_layout()
    plt.show()

def plot_Av(v1=1, v2=1, show_w=False):
    # matrix on vector
    w = A @ np.array([v1, v2])
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.quiver(0, 0, v1, v2, angles='xy', scale_units='xy', scale=1)
    if show_w:
        ax.quiver(0, 0, w[0], w[1], angles='xy', scale_units='xy', scale=1, color='red')
    ax.set_xlim([-3, 3]); ax.set_ylim([-3, 3])
    ax.set_xlabel('X'); ax.set_ylabel('Y')
    plt.tight_layout()
    plt.show()
    print(f'A = \n{A}')

def plot_evec_multiplication(v1, v2, i, show_evec, show_av):
    # i is the index of the eigenvector
    # The matrix A is defined globally
    eigvals, eigvecs = np.linalg.eig(A)
    w = A @ np.array([v1, v2])
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.quiver(0, 0, v1, v2, angles='xy', scale_units='xy', scale=1)
    if show_evec:
        ax.quiver(0, 0, eigvecs[0, i], eigvecs[1, i], angles='xy', scale_units='xy', scale=1, color='red')
    if show_av:
        ax.quiver(0, 0, w[0], w[1], angles='xy', scale_units='xy', scale=1, color='green')
    ax.set_xlim([-3, 3]); ax.set_ylim([-3, 3])
    ax.set_xlabel('X'); ax.set_ylabel('Y')
    plt.tight_layout()
    plt.show()
    print(f'w[{i}] = \n{eigvecs[:, i]}')
    print(f'λ[{i}] = {eigvals[i]}')

## §3.1 Vectors

A vector $v \in \R^n$ represents a point 

$$
v = (v_1, v_2, \dots, v_n)\tr
$$

in $n$-dimensional space where each $v_i$ is a number.

<br></br><br></br><br></br>
<br></br><br></br><br></br>

In [14]:
# plot a vector as an arrow in 3 space
@interact(v1=(-3.0, 3.5, 0.5), v2=(-3.0, 3.5, 0.5), v3=(-3.0, 3.5, 0.5))
def _(**kwargs):
    plot_v(**kwargs)

interactive(children=(FloatSlider(value=0.0, description='v1', max=3.5, min=-3.0, step=0.5), FloatSlider(value…

<br></br><br></br><br></br>
<br></br><br></br><br></br>

Given two vectors 

$$
\eq{
v &= (v_1, v_2, \dots v_n)\tr\\
w &= (w_1, w_2, \dots, w_n)\tr
}
$$

the addition of $v$ and $w$ is given by

$$
v+w = (v_1 + w_1, v_2 + w_2, \dots, v_n + w_n)\tr
$$

In [15]:
# %pip install numpy
import numpy as np

v = np.array([1, 2, 3])
w = np.array([1, 2, 3])
v + w

array([2, 4, 6])

In [16]:
# add two vectors
@interact(
    v1=(-3.0, 3.5, 0.5), v2=(-3.0, 3.5, 0.5), v3=(-3.0, 3.5, 0.5), 
    w1=(-3.0, 3.5, 0.5), w2=(-3.0, 3.5, 0.5), w3=(-3.0, 3.5, 0.5), 
)
def _(**kwargs):
    plot_vw(**kwargs)

interactive(children=(FloatSlider(value=0.0, description='v1', max=3.5, min=-3.0, step=0.5), FloatSlider(value…

In [17]:
# Vector addition


### **Two types of "products" of vectors**

1. **dot product**

The dot product of two vectors $u, v \in \R^n$ is the sum of the element-wise product

$$
u \tr v = \sum_{i=1}^n u_i v_i
$$

The geometric interpretation of the dot product is given by:

$$
u \tr v = \|{u}\| \|{v}\| \cos\Big(\angle \theta(u, v)\Big)
$$

In [18]:
@interact(u1=(-2, 2, 0.5), u2=(-2, 2, 0.5), v1=(-2, 2, 0.5), v2=(-2, 2, 0.5))
def _(**kwargs):
    plot_dotv(**kwargs)

interactive(children=(FloatSlider(value=0.0, description='u1', max=2.0, min=-2.0, step=0.5), FloatSlider(value…


<br></br><br></br><br></br>
<br></br><br></br><br></br>

2. **cross product**

The cross product of two vectors $u, v \in \R^n$ the vector $w$ which is perpendicular to the linear space _spanned_ by $u$ and $v$, i.e.,
$$
w \perp \text{span}\{u, v\}
$$
and whose magnitude is 
$$
\|w\| = \|u\| \|v\| \sin\big(\angle\theta(u, v)\big)
$$

In [19]:
@interact(u1=(-2, 2, 0.5), u2=(-2, 2, 0.5), v1=(-2, 2, 0.5), v2=(-2, 2, 0.5))
def _(**kwargs): 
    plot_crossv(**kwargs)

interactive(children=(FloatSlider(value=0.0, description='u1', max=2.0, min=-2.0, step=0.5), FloatSlider(value…

## §3.2: Linear Algebra on Vectors/Matrices

The transformation of a vector $v \in \R^n$ by a matrix $A \in \R^{m \times n}$ is another vector $w= f_A(v) = Av \in \R^m$ whose components are given by

$$
\eq{
    w_{1} &= \sum_{j=1}^n A_{1j}v_{j}\\
    w_{2} &= \sum_{j=1}^n A_{2j}v_{j}\\
    &\vdots\\
    w_{m} &= \sum_{j=1}^n A_{mj}v_{j}
}
$$

In [20]:
# declare matrix
A = np.array([
        [1.0, -1.0],
        [-1.0, 1.0],
    ])
A

array([[ 1., -1.],
       [-1.,  1.]])

In [21]:
A = np.array([
        [1.0, -2.0],
        [-1.0, 1.0]
    ])
@interact(v1=(-3.0, 3.5, 0.5), v2=(-3.0, 3.5, 0.5), show_w=False)
def _(**kwargs):
    plot_Av(**kwargs)

interactive(children=(FloatSlider(value=0.0, description='v1', max=3.5, min=-3.0, step=0.5), FloatSlider(value…

In [22]:
# Action of a Matrix on a vector

A = np.array([[1, -1], [-1, 1]])
v = np.array([2,3])
A @ v


# Matrix-matrix product
A @ A

array([[ 2, -2],
       [-2,  2]])

## §3.3: Eigenvalues and Eigenvectors

Given a **square matrix** $A$, one might ask if there exists a vector $v$ such that

$$
Av = \lambda v
$$

where $\lambda$ is a scalar. 

That is, is there a vector $v$ associated with the matrix $A$ such that when $A$ is applied to $v$, the result is a scalar multiple of $v$?

<br></br><br></br><br></br>
<br></br><br></br><br></br>

**Answer**: Yes, such vectors $v$ are called **eigenvectors** and the corresponding scalars $\lambda$ are called **eigenvalues**. 



<br></br><br></br><br></br>
<br></br><br></br><br></br>

Every square $n\times n$ matrix $A$ has $n$ eigenvectors 
$$
v_1, v_2, \dots v_n
$$ 
and $n$ corresponding eigenvalues 
$$
\lambda_1, \lambda_2, \dots, \lambda_n \in \mathbb{C} \tag{General Matrix}
$$ 

On the other hand, if the matrix $A$ is **symmetric**, then all the eigenvalues are real, i.e., 

$$
\lambda_1, \lambda_2, \dots, \lambda_n \in \mathbb{R} \tag{Symmetric Matrix}
$$

Furthermore, if the matrix $A$ is **positive definite**, then all the eigenvalues are positive, i.e.,

$$
\lambda_1, \lambda_2, \dots, \lambda_n > 0 \tag{Symmetric, PD Matrix}
$$

In [23]:
# Eigenvalues
a = np.random.randn(2, 2)
A = a @ a.T

# compute eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f'Eigenvalues of A are \n{eigenvalues}\n\n')
print(f'Eigenvectors of A are \n{eigenvectors}\n\n')

Eigenvalues of A are 
[7.6163133  1.55068591]


Eigenvectors of A are 
[[ 0.84743427 -0.53090033]
 [ 0.53090033  0.84743427]]




Let's confirm that the eigenvectors truly satisfy the equation $Av = \lambda v$.

In [31]:
@interact(v1=(-3.0, 3.5, 0.25), v2=(-3.0, 3.5, 0.25), i=(0, 1), show_evec=False, show_av=False)
def _(**kwargs): 
    plot_evec_multiplication(**kwargs)

interactive(children=(FloatSlider(value=0.25, description='v1', max=3.5, min=-3.0, step=0.25), FloatSlider(val…


<br></br><br></br><br></br>
<br></br><br></br><br></br>

Properties of eigenvalues and eigenvectors:

1. The sum of the eigenvalues of a matrix is equal to the trace of the matrix, i.e.,
$$
\sum_{i=1}^n \lambda_i = \text{trace}(A)
$$

2. The product of the eigenvalues of a matrix is equal to the determinant of the matrix, i.e.,
$$
\prod_{i=1}^n \lambda_i = \text{det}(A)
$$

3. The rank of a matrix is equal to the number of non-zero eigenvalues
$$
\text{rank}(A) = \text{number of non-zero eigenvalues}
$$

4. The eigenvectors are orthonormal
$$\eq{
v_i\tr v_j = 0 &\text{ if } i \neq j\\
v_i\tr v_j = 1 &\text{ if } i = j
}$$

## §3.3: The most important use of matrices

An $n \times m$ **matrix** $A$, is used to encode a system of $n$ linear equations in $m$ unknowns as follows:


Consider $4$ unknown variables satisfying a system of $4$ linear equations given by

$$
\begin{aligned}
10 &= a + 2b + 3c + 4d\\
9 &= 2a + 10b - 2c + 2d\\
11 &= -a + b + 10c - 4d\\
1 &= 3a - 2b + c/2 + d
\end{aligned}
$$


<br></br><br></br><br></br>
<br></br><br></br><br></br>


This is equivalently given by:

$$
b = A x
$$

where


<br></br><br></br><br></br>
<br></br><br></br><br></br>


$$
b = 
\begin{pmatrix}
10 \\
9 \\
11\\
1
\end{pmatrix}
\quad 
A = 
\begin{pmatrix}
1  &  2    & 3 & 4\\
2  &  10   & - 2 & 2\\
-1 &  1    & 10 & -4\\
3   & -2   & 1/2 & 1
\end{pmatrix}
\quad
x = \begin{pmatrix}
a \\
b \\
c\\
d
\end{pmatrix}
$$


<br></br><br></br><br></br>
<br></br><br></br><br></br>


The solution for $x$ is, then, given by

$$
\boxed{x = A^{-1}b}
$$



<br></br><br></br><br></br>
<br></br><br></br><br></br>


In [25]:
b = np.array([10, 9, 11, 1])

A = np.array([
    [1, 2, 3, 4],
    [2, 10, -2, 2],
    [-1, 1, 10, -4],
    [2, -2, 1/2, 1],
])


# two ways of solving for x
print(f' inv(A) @ b = {np.linalg.inv(A) @ b}')
print(f' solve(A, b) = {np.linalg.solve(A, b)}')

 inv(A) @ b = [0.61588181 0.89012004 1.4099723  0.8434903 ]
 solve(A, b) = [0.61588181 0.89012004 1.4099723  0.8434903 ]


## §3.2 Data Summarization

In [26]:
# Mean function is exported by numpy
?np.mean


# It is available to the class of np.arrays
x = np.random.rand(10)
np.mean(x)


# Numpy implicitly applies the operation to the class of base python lists
y = [1, 2, 3, 4, 5, 6, 7]
np.mean(y) # converts it to np.array and then computes mean


4.0

Signature:      
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Call signature:  np.mean(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function mean at 0x10827a5c0>
File:            ~/Library/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/numpy/core/fromnumeric.py
Docstring:      
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    I

In [27]:
# Row-wise and column-wise means
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(f'row means  = {A.mean(axis=1)}')
print(f'column means = {A.mean(axis=0)}')

row means  = [2. 5. 8.]
column means = [4. 5. 6.]


## §3.3 What Python Knows in this session

In [28]:
%who

A	 a	 b	 eigenvalues	 eigenvectors	 fib	 fibonacci	 fixed	 i	 
interact	 interact_manual	 interactive	 ipywidgets	 k	 math	 n	 np	 pd	 
plot_Av	 plot_crossv	 plot_dotv	 plot_evec_multiplication	 plot_v	 plot_vw	 plt	 v	 w	 
x	 y	 


#### §3.4.1 Deleting variables from workspace

In [29]:
# del(A, x)

---